### ISSUE TITLE
screenshots in your README.md

### ISSUE THREAD

**Issue by sebma** [redddcyclone/glpi-agentmonitor#12]
Hi,

Can you please add some screenshots URLs in your README.md, like these ?

![image](https://github.com/redddcyclone/glpi-agentmonitor/assets/4569306/4cf95b00-7bcd-4edc-8b79-50a7482609fe)

![image](https://github.com/redddcyclone/glpi-agentmonitor/assets/4569306/cde7e794-6467-4e4b-b397-9e0df0f46482)

**Comment by redddcyclone** [comment]
Hi @sebma 

I added the main window screenshot to the `README.md` file. I thought it was not necessary to add a screenshot of the right-click menu as it has the same options the main window has.

Thanks for the suggestion!

**Comment by sebma** [comment]
@redddcyclone Thanks 👍
