### ISSUE TITLE
Request: Spanish (Uruguay) translation update

### ISSUE THREAD

**Issue by redddcyclone** [redddcyclone/glpi-agentmonitor#20]
Hi @Iruxos 

A new settings dialog was added to GLPI Agent Monitor, to allow setting the New Ticket page URL. We need to translate some strings to the Spanish (Uruguay) language, could you help us again?

Thanks in advance!

**Comment by Iruxos** [comment]
Sure, I can help with the translation.

**Comment by redddcyclone** [comment]
Hi @Iruxos 

Okay! The new strings are already on the master branch, you can view them on the string table for the English or Portuguese (Brazil) languages.

Thanks a lot!

**Comment by g-bougard** [comment]
Hi @Iruxos 

I'm about to release a new version, see #23. I still can include a translation update before the real release ;-)

**Comment by g-bougard** [comment]
Hi @Iruxos 

sorry, we released 1.3.0 but we still wait your contribution for a future version.

**Comment by redddcyclone** [comment]
Hi @Iruxos 

A new setting was just added and, with it, two new strings. Could we count with your help for updating them, along with the ones already requested in this issue?

Thanks a lot!

**Comment by bertugarangou** [comment]
Hello, I can help with the Spanish translation. I am from Spain so my Spanish may be different on some words but as far as I can see on the strings, there is no difference on this topic. I'd like to avoid stepping on someone else's work, so I'm asking in advance.
Thnks!

**Comment by redddcyclone** [comment]
Hi @bertugarangou 

Of course, feel free to help with this if you feel confident to do so! Any help is welcome!

**Comment by bertugarangou** [comment]
Updated translations, #31 , ask me anything if I did anything wrong!

**Comment by redddcyclone** [comment]
Hi @bertugarangou 

Looks like everything is fine. Thanks a lot for the help with the translation!

**Comment by redddcyclone** [comment]
@bertugarangou 

I changed the Spanish string table to a neutral sublanguage. Could you download and test the artifact that was built for commit bd33bdd ([here](https://github.com/redddcyclone/glpi-agentmonitor/actions/runs/10793103428)) on your system to see if it display the language correctly?

**Comment by bertugarangou** [comment]
<img src="https://github.com/user-attachments/assets/8889e5fd-506b-4282-8afb-170f758413c5" alt="screenshot" width=50% height=50%>
<br>
Seems good!
Also tried some erros msgs and are OK too.

**Comment by redddcyclone** [comment]
Hi @bertugarangou 

Great, thanks a lot for the help!
