### ISSUE TITLE
New ticket opens explorer on C:\Windows\System32

### ISSUE THREAD

**Issue by SteadEXE** [redddcyclone/glpi-agentmonitor#24]
Hello,

After installing latest version of the agent, new ticket button does not open browser, but explorer in directory: C:\Windows\System32
In the code there is a check to fallback to default URL, but I think it does not handle empty strings.

To reproduce the issue, the registry key needs to be empty.

EDIT: It looks like it has been fixed there, but not in forked version of GLPI

**Comment by redddcyclone** [comment]
Hi @SteadEXE 

Yes, I did add a check for the empty registry value.

@g-bougard, could you check this question? Seems like you didn't merge commit a8d88752 on the forked repo

Thanks a lot!
