### ISSUE TITLE
Request: Dutch translation update

### ISSUE THREAD

**Issue by redddcyclone** [redddcyclone/glpi-agentmonitor#29]
Hi @perplexityjeff 

Some new strings were added in the settings dialog. We need to translate some strings to the Dutch language, could you help us again with this?

Thanks in advance!

**Comment by perplexityjeff** [comment]
Hi @redddcyclone,

Just to confirm do you require the following strings translated in the pull requests?

IDS_SETTINGS_NEWTICKET
IDS_SETTINGS_NEWTICKET_SCREENSHOT 

Thanks,

Jeff

**Comment by redddcyclone** [comment]
@perplexityjeff 

Yes, these were the only strings I added.

**Comment by perplexityjeff** [comment]
Hi @redddcyclone,

I have created a pull request. I hope that I've done it correctly :).

https://github.com/redddcyclone/glpi-agentmonitor/pull/30

Thanks,

Jeff

**Comment by redddcyclone** [comment]
Hi @perplexityjeff 

Everything is fine, thanks a lot for contributing again!!
