### ISSUE TITLE
Need to support Restart Manager

### ISSUE THREAD

**Issue by g-bougard** [redddcyclone/glpi-agentmonitor#4]
Hi @redddcyclone 

I'm facing a problem when trying to include the binary in MSI packaging. It doesn't support Restart Manager messages so we are always prompted to close the app.

It seems to me you have to follow this doc:
https://learn.microsoft.com/en-us/windows/win32/rstmgr/guidelines-for-applications

I tried to use [CloseApplication wix definition](https://wixtoolset.org/docs/schema/util/closeapplication/) but even WM_CLOSE message is not supported as you're only supporting the one triggered from the systray [as you require specific parameters to close the app](https://github.com/redddcyclone/glpi-agentmonitor/blob/7412aaa6e4db58ca542332f2f4608378f9a00afe/GLPI-AgentMonitor.cpp#L754). Supporting WM_QUERYENDSESSION & WM_ENDSESSION as explained in Restart Manager documentation should be fine.

**Comment by redddcyclone** [comment]
Hi @g-bougard 

I followed the document you mentioned, but I can't test if it worked. Could you test it?

**Comment by g-bougard** [comment]
Thank you very much, I will test tomorrow.

**Comment by g-bougard** [comment]
I identified a problem with your message handling. For `WM_QUERYENDSESSION` you return **TRUE**, but we are in a [Dlgproc callback](https://learn.microsoft.com/en-us/windows/win32/api/winuser/nc-winuser-dlgproc) for a dialog [created by CreateDialog()](https://github.com/redddcyclone/glpi-agentmonitor/blob/4b3ab2cbb8af81c7033cb67ebda188fe8e1617c4/GLPI-AgentMonitor.cpp#L543). In that case, the return value has explained in doc is there to tell if the message was handled. Maybe you should even check is the returned value is correct here for all other message kinds. Anyway, as explained in the Dlgproc doc, the way to return a value to the caller is to use something like *[SetWindowLong](https://learn.microsoft.com/en-us/windows/desktop/api/winuser/nf-winuser-setwindowlonga)(hwndDlg, DWL_MSGRESULT, lResult)*.

So if I use the following code, `WM_QUERYENDSESSION` is correctly handled:
```C++
        case WM_QUERYENDSESSION:
        {
            if (lParam == ENDSESSION_CLOSEAPP) {
                SetWindowLong(hWnd, 0, TRUE);
                return TRUE;
            }
            break;
        }
```
Here I put `0` as second argument as I don't know why `DWL_MSGRESULT` is not recognized in my local built environment. So try first with the `DWL_MSGRESULT` symbol as maybe it's okay in yours or in GH Actions environment.

I still need to make some tests to find the best installation process.

**Comment by redddcyclone** [comment]
Oh, I didn't know it would be a different procedure for handling dialog messages. Actually, I didn't even know I should return TRUE in the callback to inform that the message has been handled successfully (so as of now, all messages are being returned as not being handled). I'll fix this and try your suggestion right away.

**Comment by redddcyclone** [comment]
@g-bougard 
I've just made the change you suggested and placed `return TRUE;` on places where I think the messages should be considered as processed successfully. Also, `SetWindowLong` does not work on 64-bit platforms, and `WinUser.h` undefines `DWL_MSGRESULT` when `_WIN64` is defined. So I used its replacement, `SetWindowLongPtr` with `DWLP_MSGRESULT`. Please try it and report back.

**Comment by g-bougard** [comment]
I can now easily stop GLPI-AgentMonitor from an installer.
Thank you.
